services:
  - type: web
    name: travel-system-backend
    env: node
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
